name: Translate Articles

on:
  push:
    paths:
      - 'articles/**'
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    environment: DeepL
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Check environment variable
        run: echo "DEEPL_API_KEY is set"
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}

      - name: Fetch full git history
        run: git fetch --unshallow

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Authenticate with GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}

      - name: Run translation script
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        run: node translate.js

        - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Add translated articles"
          git push
